package databack;

import com.gtnewhorizon.gtnhlib.config.Config;

@Config(modid = Databack.MODID)
public class DatabackConfig {

    @Config.Comment("Dump .class files generated by the density function bytecode compiler. Useful for inspecting generated bytecode.")
    @Config.DefaultBoolean(false)
    public static boolean dumpCompiledDensityFunctions;

    @Config.Comment("Directory to write compiled density function .class files into. Relative to the Minecraft run directory.")
    @Config.DefaultString("compiled-df")
    public static String compiledDensityFunctionDumpDir;

    @Config.Comment("Enable block/item/biome/entity tag debug mode")
    @Config.DefaultBoolean(true)
    public static boolean enableTagDebugMode;

}
