package databack.common.interop.registry;

import net.minecraft.util.ResourceLocation;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import databack.Databack;
import it.unimi.dsi.fastutil.Pair;

/// A wrapper around another registry that provides a [ResourceLocation] <-> object lookup.
/// This is used as a shim around 1.7's registries, because modern's registries are much more formal than ours, and they
/// have a better introspection interface.
public interface IProxyRegistry<T> extends Iterable<Pair<ResourceLocation, T>> {

    Logger LOGGER = LogManager.getLogger(Databack.MODID + "|registry");

    T getObject(ResourceLocation id);
    ResourceLocation getIdForObject(T object);

    /// Cleans a human name into a 'good enough' snake_case id. Some names (such as `XPOrb`) get mangled (into `xporb`),
    /// but for the most part this works well.
    /// ```
    /// Foo Bar -> foo_bar
    /// FooBar -> foo_bar
    /// Foo_Bar -> foo_bar
    /// Foo-Bar -> foo_bar
    /// foo bar -> foo_bar
    /// etc
    /// ```
    static String cleanId(String human) {
        String underscores = "";

        // First step: normalize separators into underscores
        for (char curr : human.toCharArray()) {
            char lastChar = underscores.isEmpty() ? 0 : underscores.charAt(underscores.length() - 1);

            if (curr == ' ' || curr == '_' || curr == '-') {
                if (lastChar != '_') {
                    underscores += '_';
                }

                continue;
            }

            underscores += curr;
        }

        String cleaned = "";

        char[] us_chars = underscores.toCharArray();

        // Second step: convert PascalCase into snake_case, keeping any separators generated by the previous step
        for (int i = 0; i < us_chars.length; i++) {
            char curr = us_chars[i];

            if (i > 0) {
                char prev = us_chars[i - 1];

                if (Character.isAlphabetic(prev) && Character.isAlphabetic(curr) && !Character.isUpperCase(prev) && Character.isUpperCase(curr)) {
                    cleaned += '_';
                }
            }

            cleaned += Character.toLowerCase(curr);
        }

        return cleaned;
    }
}
